### ISSUE TITLE
tag$script update

### ISSUE THREAD

**Issue by Alverga** [shinyonfire/sof-auth-example#6]
Hello Andy, thank you for sharing this example, very interesting solution, i am still learning about it. I have reproduced here and it worked, but only after a modification:
In ui.r (lines 7 and 8) i a had to change the 5.7.0 version (i guess)
 tags$script(src="https://www.gstatic.com/firebasejs/5.7.0/firebase-app.js"),
 tags$script(src="https://www.gstatic.com/firebasejs/5.7.0/firebase-auth.js"),

to 5.8.4 - 

tags$script(src="https://www.gstatic.com/firebasejs/5.8.4/firebase-app.js"),
tags$script(src="https://www.gstatic.com/firebasejs/5.8.4/firebase-auth.js"),

As i was not getting any response when i clicked the sign in button. My question is, do i have to be looking every day for changes in this version, made by firebase team? In order to keep these links updated?

**Comment by merlinoa** [comment]
In order to use the most recent version of Firebase you do need to update those scripts src references to the more recent version -- as you did above.  

However, you should have been able to use version Firebase app and auth versions 5.7.0 to run this demo app without issues, so I am not sure why that was not working for you.

**Comment by Alverga** [comment]
Thank you Andy, It was probably a coincidence, i suppose it should work fine with older version .
